CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    hotel_id VARCHAR(255) NOT NULL,
    promo_code VARCHAR(255),
    discount_percent DOUBLE PRECISION NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

INSERT INTO bookings (id, user_id, hotel_id, promo_code, discount_percent, price, created_at)
VALUES (1, 'user1', 'h1', 'SUMMER', 20.0, 80.0, '2026-07-27T00:00:00Z')
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('bookings', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM bookings), 1),
    true
);
